// COPY. Everything below this note is a verbatim copy of the conversion
// table used by the mdisbetter.com website, French comments included.
// Do not edit it here: edit nothing, regenerate it. See the README,
// section "Where the conversion table comes from".
//
// 3649 proven pairs, 162 accepted input extensions.
// Synced by scripts/synchroniser-mcp.mjs, never by hand.

// Ce que le produit sait convertir, et par quelle route.
//
// GENERE, ne pas editer a la main. Source : media-service/paires-prouvees.md.
//
// Ce fichier ne contient QUE des paires prouvees, c'est-a-dire dont la
// sonde a relu la sortie et reconnu le format, mot temoin compris. Les
// listes que le moteur declare sont plus larges : declarer n'est pas
// prouver, et l'interface ne doit jamais proposer ce qui echouera.
//
// Une extension peut appartenir a deux familles : calibre et pandoc
// lisent tous deux docx, epub, odt, rtf, txt et md. La table tranche
// donc pour chaque paire, et l'utilisateur n'a pas a connaitre cette
// distinction : il depose un fichier et choisit une sortie.

export const RELEVE_LE = '2026-08-30';

/** source -> { cible: famille qui sert la paire }. */
export const PAIRES = {
  '3g2': { '3gp': 'media', aac: 'media', ac3: 'media', aiff: 'media', au: 'media', avi: 'media', caf: 'media', eac3: 'media', flac: 'media', flv: 'media', gif: 'media', m4a: 'media', m4v: 'media', mka: 'media', mkv: 'media', mov: 'media', mp2: 'media', mp3: 'media', mp4: 'media', mpg: 'media', ogg: 'media', ogv: 'media', opus: 'media', spx: 'media', ts: 'media', tta: 'media', wav: 'media', webm: 'media', wma: 'media', wmv: 'media', wv: 'media' },
  '3gp': { aac: 'media', ac3: 'media', aiff: 'media', au: 'media', avi: 'media', caf: 'media', eac3: 'media', flac: 'media', flv: 'media', gif: 'media', m4a: 'media', m4v: 'media', mka: 'media', mkv: 'media', mov: 'media', mp2: 'media', mp3: 'media', mp4: 'media', mpg: 'media', ogg: 'media', ogv: 'media', opus: 'media', spx: 'media', ts: 'media', tta: 'media', wav: 'media', webm: 'media', wma: 'media', wmv: 'media', wv: 'media' },
  '7z': { tar: 'archive', tbz2: 'archive', tgz: 'archive', txz: 'archive', zip: 'archive' },
  aac: { ac3: 'media', aiff: 'media', au: 'media', caf: 'media', eac3: 'media', flac: 'media', m4a: 'media', mka: 'media', mp2: 'media', mp3: 'media', ogg: 'media', opus: 'media', spx: 'media', tta: 'media', wav: 'media', wma: 'media', wv: 'media' },
  ac3: { aac: 'media', aiff: 'media', au: 'media', caf: 'media', eac3: 'media', flac: 'media', m4a: 'media', mka: 'media', mp2: 'media', mp3: 'media', ogg: 'media', opus: 'media', spx: 'media', tta: 'media', wav: 'media', wma: 'media', wv: 'media' },
  aif: { aac: 'media', ac3: 'media', aiff: 'media', au: 'media', caf: 'media', eac3: 'media', flac: 'media', m4a: 'media', mka: 'media', mp2: 'media', mp3: 'media', ogg: 'media', opus: 'media', spx: 'media', tta: 'media', wav: 'media', wma: 'media', wv: 'media' },
  aiff: { aac: 'media', ac3: 'media', au: 'media', caf: 'media', eac3: 'media', flac: 'media', m4a: 'media', mka: 'media', mp2: 'media', mp3: 'media', ogg: 'media', opus: 'media', spx: 'media', tta: 'media', wav: 'media', wma: 'media', wv: 'media' },
  asf: { '3gp': 'media', aac: 'media', ac3: 'media', aiff: 'media', au: 'media', avi: 'media', caf: 'media', eac3: 'media', flac: 'media', flv: 'media', gif: 'media', m4a: 'media', m4v: 'media', mka: 'media', mkv: 'media', mov: 'media', mp2: 'media', mp3: 'media', mp4: 'media', mpg: 'media', ogg: 'media', ogv: 'media', opus: 'media', spx: 'media', ts: 'media', tta: 'media', wav: 'media', webm: 'media', wma: 'media', wmv: 'media', wv: 'media' },
  ass: { lrc: 'subtitle', srt: 'subtitle', ssa: 'subtitle', ttml: 'subtitle', vtt: 'subtitle' },
  au: { aac: 'media', ac3: 'media', aiff: 'media', caf: 'media', eac3: 'media', flac: 'media', m4a: 'media', mka: 'media', mp2: 'media', mp3: 'media', ogg: 'media', opus: 'media', spx: 'media', tta: 'media', wav: 'media', wma: 'media', wv: 'media' },
  avi: { '3gp': 'media', aac: 'media', ac3: 'media', aiff: 'media', au: 'media', caf: 'media', eac3: 'media', flac: 'media', flv: 'media', gif: 'media', m4a: 'media', m4v: 'media', mka: 'media', mkv: 'media', mov: 'media', mp2: 'media', mp3: 'media', mp4: 'media', mpg: 'media', ogg: 'media', ogv: 'media', opus: 'media', spx: 'media', ts: 'media', tta: 'media', wav: 'media', webm: 'media', wma: 'media', wmv: 'media', wv: 'media' },
  avif: { bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  azw: { azw3: 'ebook', docx: 'ebook', epub: 'ebook', fb2: 'ebook', htmlz: 'ebook', lit: 'ebook', lrf: 'ebook', mobi: 'ebook', pdb: 'ebook', pdf: 'ebook', pmlz: 'ebook', rb: 'ebook', rtf: 'ebook', tcr: 'ebook', txt: 'ebook', txtz: 'ebook' },
  azw3: { docx: 'ebook', epub: 'ebook', fb2: 'ebook', htmlz: 'ebook', lit: 'ebook', lrf: 'ebook', mobi: 'ebook', pdb: 'ebook', pdf: 'ebook', pmlz: 'ebook', rb: 'ebook', rtf: 'ebook', tcr: 'ebook', txt: 'ebook', txtz: 'ebook' },
  biblatex: { bibtex: 'bibliography', csljson: 'bibliography' },
  bibtex: { biblatex: 'bibliography', csljson: 'bibliography' },
  bmp: { avif: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  caf: { aac: 'media', ac3: 'media', aiff: 'media', au: 'media', eac3: 'media', flac: 'media', m4a: 'media', mka: 'media', mp2: 'media', mp3: 'media', ogg: 'media', opus: 'media', spx: 'media', tta: 'media', wav: 'media', wma: 'media', wv: 'media' },
  cin: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  creole: { adoc: 'document', context: 'document', docbook: 'document', docx: 'document', dokuwiki: 'document', epub: 'document', fb2: 'document', gfm: 'document', html: 'document', icml: 'document', ipynb: 'document', jats: 'document', jira: 'document', json: 'document', man: 'document', md: 'document', mediawiki: 'document', ms: 'document', muse: 'document', odt: 'document', opml: 'document', org: 'document', rst: 'document', rtf: 'document', tei: 'document', tex: 'document', texi: 'document', textile: 'document', txt: 'document', typst: 'document', zimwiki: 'document' },
  csljson: { biblatex: 'bibliography', bibtex: 'bibliography' },
  csv: { context: 'document', docbook: 'document', docx: 'document', dokuwiki: 'document', epub: 'document', gfm: 'document', html: 'document', icml: 'document', ipynb: 'document', jats: 'document', jira: 'document', json: 'data', man: 'document', md: 'document', mediawiki: 'document', ms: 'document', muse: 'document', ndjson: 'data', ods: 'office', odt: 'document', org: 'document', pdf: 'office', rst: 'document', rtf: 'document', tei: 'document', tex: 'document', texi: 'document', textile: 'document', tsv: 'data', txt: 'document', typst: 'document', xlsx: 'office', yaml: 'data', zimwiki: 'document' },
  cur: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  dds: { avif: 'image', bmp: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  doc: { docx: 'office', html: 'office', odt: 'office', pdf: 'office', rtf: 'office', txt: 'office' },
  docbook: { adoc: 'document', context: 'document', docx: 'document', dokuwiki: 'document', epub: 'document', fb2: 'document', gfm: 'document', html: 'document', icml: 'document', ipynb: 'document', jats: 'document', jira: 'document', json: 'document', man: 'document', markua: 'document', md: 'document', mediawiki: 'document', ms: 'document', muse: 'document', odt: 'document', opml: 'document', org: 'document', rst: 'document', rtf: 'document', tei: 'document', tex: 'document', texi: 'document', textile: 'document', txt: 'document', typst: 'document', xwiki: 'document', zimwiki: 'document' },
  docx: { adoc: 'document', azw3: 'ebook', context: 'document', docbook: 'document', dokuwiki: 'document', epub: 'document', fb2: 'document', gfm: 'document', html: 'document', htmlz: 'ebook', icml: 'document', ipynb: 'document', jats: 'document', jira: 'document', json: 'document', lit: 'ebook', lrf: 'ebook', man: 'document', markua: 'document', md: 'document', mediawiki: 'document', mobi: 'ebook', ms: 'document', muse: 'document', odt: 'office', opml: 'document', org: 'document', pdb: 'ebook', pdf: 'office', pmlz: 'ebook', rb: 'ebook', rst: 'document', rtf: 'office', tcr: 'ebook', tei: 'document', tex: 'document', texi: 'document', textile: 'document', txt: 'document', txtz: 'ebook', typst: 'document', xwiki: 'document', zimwiki: 'document' },
  dokuwiki: { adoc: 'document', context: 'document', docbook: 'document', docx: 'document', epub: 'document', fb2: 'document', gfm: 'document', html: 'document', icml: 'document', ipynb: 'document', jats: 'document', jira: 'document', json: 'document', man: 'document', markua: 'document', md: 'document', mediawiki: 'document', ms: 'document', muse: 'document', odt: 'document', opml: 'document', org: 'document', rst: 'document', rtf: 'document', tei: 'document', tex: 'document', texi: 'document', textile: 'document', txt: 'document', typst: 'document', xwiki: 'document', zimwiki: 'document' },
  dpx: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  dv: { '3gp': 'media', aac: 'media', ac3: 'media', aiff: 'media', au: 'media', avi: 'media', caf: 'media', eac3: 'media', flac: 'media', flv: 'media', gif: 'media', m4a: 'media', m4v: 'media', mka: 'media', mkv: 'media', mov: 'media', mp2: 'media', mp3: 'media', mp4: 'media', mpg: 'media', ogg: 'media', ogv: 'media', opus: 'media', spx: 'media', ts: 'media', tta: 'media', wav: 'media', webm: 'media', wma: 'media', wmv: 'media', wv: 'media' },
  eac3: { aac: 'media', ac3: 'media', aiff: 'media', au: 'media', caf: 'media', flac: 'media', m4a: 'media', mka: 'media', mp2: 'media', mp3: 'media', ogg: 'media', opus: 'media', spx: 'media', tta: 'media', wav: 'media', wma: 'media', wv: 'media' },
  endnotexml: { biblatex: 'bibliography', bibtex: 'bibliography', csljson: 'bibliography' },
  eps: { avif: 'image', bmp: 'image', dds: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  epub: { adoc: 'document', azw3: 'ebook', context: 'document', docbook: 'document', docx: 'document', dokuwiki: 'document', fb2: 'document', gfm: 'document', html: 'document', htmlz: 'ebook', icml: 'document', ipynb: 'document', jats: 'document', jira: 'document', json: 'document', lit: 'ebook', lrf: 'ebook', man: 'document', md: 'document', mediawiki: 'document', mobi: 'ebook', ms: 'document', odt: 'document', opml: 'document', org: 'document', pdb: 'ebook', pdf: 'ebook', pmlz: 'ebook', rb: 'ebook', rst: 'document', rtf: 'document', tcr: 'ebook', tei: 'document', tex: 'document', texi: 'document', textile: 'document', txt: 'document', txtz: 'ebook', xwiki: 'document', zimwiki: 'document' },
  f4v: { '3gp': 'media', aac: 'media', ac3: 'media', aiff: 'media', au: 'media', avi: 'media', caf: 'media', eac3: 'media', flac: 'media', flv: 'media', gif: 'media', m4a: 'media', m4v: 'media', mka: 'media', mkv: 'media', mov: 'media', mp2: 'media', mp3: 'media', mp4: 'media', mpg: 'media', ogg: 'media', ogv: 'media', opus: 'media', spx: 'media', ts: 'media', tta: 'media', wav: 'media', webm: 'media', wma: 'media', wmv: 'media', wv: 'media' },
  fb2: { adoc: 'document', azw3: 'ebook', context: 'document', docbook: 'document', docx: 'document', dokuwiki: 'document', epub: 'document', gfm: 'document', html: 'document', htmlz: 'ebook', icml: 'document', ipynb: 'document', jats: 'document', jira: 'document', json: 'document', lit: 'ebook', lrf: 'ebook', man: 'document', md: 'document', mediawiki: 'document', mobi: 'ebook', ms: 'document', muse: 'document', odt: 'document', opml: 'document', org: 'document', pdb: 'ebook', pdf: 'ebook', pmlz: 'ebook', rb: 'ebook', rst: 'document', rtf: 'document', tcr: 'ebook', tei: 'document', tex: 'document', texi: 'document', textile: 'document', txt: 'document', txtz: 'ebook', typst: 'document', xwiki: 'document', zimwiki: 'document' },
  fits: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', pbm: 'image', pcx: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', wbmp: 'image', xpm: 'image' },
  flac: { aac: 'media', ac3: 'media', aiff: 'media', au: 'media', caf: 'media', eac3: 'media', m4a: 'media', mka: 'media', mp2: 'media', mp3: 'media', ogg: 'media', opus: 'media', spx: 'media', tta: 'media', wav: 'media', wma: 'media', wv: 'media' },
  flv: { '3gp': 'media', aac: 'media', ac3: 'media', aiff: 'media', au: 'media', avi: 'media', caf: 'media', eac3: 'media', flac: 'media', gif: 'media', m4a: 'media', m4v: 'media', mka: 'media', mkv: 'media', mov: 'media', mp2: 'media', mp3: 'media', mp4: 'media', mpg: 'media', ogg: 'media', ogv: 'media', opus: 'media', spx: 'media', ts: 'media', tta: 'media', wav: 'media', webm: 'media', wma: 'media', wmv: 'media', wv: 'media' },
  gif: { '3gp': 'media', avi: 'media', avif: 'image', bmp: 'image', dds: 'image', eps: 'image', flv: 'media', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', m4v: 'media', miff: 'image', mkv: 'media', mov: 'media', mp4: 'media', mpg: 'media', ogv: 'media', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', ts: 'media', wbmp: 'image', webm: 'media', wmv: 'media', xpm: 'image' },
  gsm: { aac: 'media', ac3: 'media', aiff: 'media', au: 'media', caf: 'media', eac3: 'media', flac: 'media', m4a: 'media', mka: 'media', mp2: 'media', mp3: 'media', ogg: 'media', opus: 'media', spx: 'media', tta: 'media', wav: 'media', wma: 'media', wv: 'media' },
  hdr: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  heic: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  heif: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  html: { adoc: 'document', azw3: 'ebook', context: 'document', docbook: 'document', docx: 'document', dokuwiki: 'document', epub: 'document', fb2: 'document', gfm: 'document', htmlz: 'ebook', icml: 'document', ipynb: 'document', jats: 'document', jira: 'document', json: 'document', lit: 'ebook', lrf: 'ebook', man: 'document', markua: 'document', md: 'document', mediawiki: 'document', mobi: 'ebook', ms: 'document', muse: 'document', odt: 'document', opml: 'document', org: 'document', pdb: 'ebook', pdf: 'ebook', pmlz: 'ebook', rb: 'ebook', rst: 'document', rtf: 'document', tcr: 'ebook', tei: 'document', tex: 'document', texi: 'document', textile: 'document', txt: 'document', txtz: 'ebook', typst: 'document', xwiki: 'document', zimwiki: 'document' },
  htmlz: { azw3: 'ebook', docx: 'ebook', epub: 'ebook', fb2: 'ebook', lit: 'ebook', lrf: 'ebook', mobi: 'ebook', pdb: 'ebook', pdf: 'ebook', pmlz: 'ebook', rb: 'ebook', rtf: 'ebook', tcr: 'ebook', txt: 'ebook', txtz: 'ebook' },
  ico: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  ipynb: { adoc: 'document', context: 'document', docbook: 'document', docx: 'document', dokuwiki: 'document', epub: 'document', fb2: 'document', gfm: 'document', html: 'document', icml: 'document', jats: 'document', jira: 'document', json: 'document', man: 'document', markua: 'document', md: 'document', mediawiki: 'document', ms: 'document', muse: 'document', odt: 'document', org: 'document', rst: 'document', rtf: 'document', tei: 'document', tex: 'document', texi: 'document', textile: 'document', txt: 'document', typst: 'document', xwiki: 'document', zimwiki: 'document' },
  j2k: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  jira: { adoc: 'document', context: 'document', docbook: 'document', docx: 'document', dokuwiki: 'document', epub: 'document', fb2: 'document', gfm: 'document', html: 'document', icml: 'document', ipynb: 'document', jats: 'document', json: 'document', man: 'document', md: 'document', mediawiki: 'document', ms: 'document', muse: 'document', odt: 'document', opml: 'document', org: 'document', rst: 'document', rtf: 'document', tei: 'document', tex: 'document', texi: 'document', textile: 'document', txt: 'document', typst: 'document', xwiki: 'document', zimwiki: 'document' },
  jng: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  jp2: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  jpeg: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  jpg: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  json: { adoc: 'document', context: 'document', csv: 'data', docbook: 'document', docx: 'document', dokuwiki: 'document', epub: 'document', fb2: 'document', gfm: 'document', html: 'document', icml: 'document', ipynb: 'document', jats: 'document', jira: 'document', man: 'document', markua: 'document', md: 'document', mediawiki: 'document', ms: 'document', muse: 'document', ndjson: 'data', odt: 'document', opml: 'document', org: 'document', rst: 'document', rtf: 'document', tei: 'document', tex: 'document', texi: 'document', textile: 'document', toml: 'data', tsv: 'data', txt: 'document', typst: 'document', xwiki: 'document', yaml: 'data', zimwiki: 'document' },
  lit: { azw3: 'ebook', docx: 'ebook', epub: 'ebook', fb2: 'ebook', htmlz: 'ebook', lrf: 'ebook', mobi: 'ebook', pdb: 'ebook', pdf: 'ebook', pmlz: 'ebook', rb: 'ebook', rtf: 'ebook', tcr: 'ebook', txt: 'ebook', txtz: 'ebook' },
  lrc: { ass: 'subtitle', srt: 'subtitle', ssa: 'subtitle', ttml: 'subtitle', vtt: 'subtitle' },
  lrf: { azw3: 'ebook', docx: 'ebook', epub: 'ebook', fb2: 'ebook', htmlz: 'ebook', lit: 'ebook', mobi: 'ebook', pdb: 'ebook', pdf: 'ebook', pmlz: 'ebook', rb: 'ebook', rtf: 'ebook', tcr: 'ebook', txt: 'ebook', txtz: 'ebook' },
  m2ts: { '3gp': 'media', aac: 'media', ac3: 'media', aiff: 'media', au: 'media', avi: 'media', caf: 'media', eac3: 'media', flac: 'media', flv: 'media', gif: 'media', m4a: 'media', m4v: 'media', mka: 'media', mkv: 'media', mov: 'media', mp2: 'media', mp3: 'media', mp4: 'media', mpg: 'media', ogg: 'media', ogv: 'media', opus: 'media', spx: 'media', ts: 'media', tta: 'media', wav: 'media', webm: 'media', wma: 'media', wmv: 'media', wv: 'media' },
  m4a: { aac: 'media', ac3: 'media', aiff: 'media', au: 'media', caf: 'media', eac3: 'media', flac: 'media', mka: 'media', mp2: 'media', mp3: 'media', ogg: 'media', opus: 'media', spx: 'media', tta: 'media', wav: 'media', wma: 'media', wv: 'media' },
  m4b: { aac: 'media', ac3: 'media', aiff: 'media', au: 'media', caf: 'media', eac3: 'media', flac: 'media', m4a: 'media', mka: 'media', mp2: 'media', mp3: 'media', ogg: 'media', opus: 'media', spx: 'media', tta: 'media', wav: 'media', wma: 'media', wv: 'media' },
  m4v: { '3gp': 'media', aac: 'media', ac3: 'media', aiff: 'media', au: 'media', avi: 'media', caf: 'media', eac3: 'media', flac: 'media', flv: 'media', gif: 'media', m4a: 'media', mka: 'media', mkv: 'media', mov: 'media', mp2: 'media', mp3: 'media', mp4: 'media', mpg: 'media', ogg: 'media', ogv: 'media', opus: 'media', spx: 'media', ts: 'media', tta: 'media', wav: 'media', webm: 'media', wma: 'media', wmv: 'media', wv: 'media' },
  man: { adoc: 'document', context: 'document', docbook: 'document', docx: 'document', dokuwiki: 'document', epub: 'document', fb2: 'document', gfm: 'document', html: 'document', icml: 'document', ipynb: 'document', jats: 'document', jira: 'document', json: 'document', md: 'document', mediawiki: 'document', ms: 'document', muse: 'document', odt: 'document', opml: 'document', org: 'document', rst: 'document', rtf: 'document', tei: 'document', tex: 'document', texi: 'document', textile: 'document', txt: 'document', typst: 'document', zimwiki: 'document' },
  md: { adoc: 'document', azw3: 'ebook', context: 'document', docbook: 'document', docx: 'document', dokuwiki: 'document', epub: 'document', fb2: 'document', gfm: 'document', html: 'document', htmlz: 'ebook', icml: 'document', ipynb: 'document', jats: 'document', jira: 'document', json: 'document', lit: 'ebook', lrf: 'ebook', man: 'document', markua: 'document', mediawiki: 'document', mobi: 'ebook', ms: 'document', muse: 'document', odt: 'document', opml: 'document', org: 'document', pdb: 'ebook', pdf: 'ebook', pmlz: 'ebook', rb: 'ebook', rst: 'document', rtf: 'document', tcr: 'ebook', tei: 'document', tex: 'document', texi: 'document', textile: 'document', txt: 'document', txtz: 'ebook', typst: 'document', xwiki: 'document', zimwiki: 'document' },
  mediawiki: { adoc: 'document', context: 'document', docbook: 'document', docx: 'document', dokuwiki: 'document', epub: 'document', fb2: 'document', gfm: 'document', html: 'document', icml: 'document', ipynb: 'document', jats: 'document', jira: 'document', json: 'document', man: 'document', markua: 'document', md: 'document', ms: 'document', muse: 'document', odt: 'document', opml: 'document', org: 'document', rst: 'document', rtf: 'document', tei: 'document', tex: 'document', texi: 'document', textile: 'document', txt: 'document', typst: 'document', xwiki: 'document', zimwiki: 'document' },
  miff: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  mka: { aac: 'media', ac3: 'media', aiff: 'media', au: 'media', caf: 'media', eac3: 'media', flac: 'media', m4a: 'media', mp2: 'media', mp3: 'media', ogg: 'media', opus: 'media', spx: 'media', tta: 'media', wav: 'media', wma: 'media', wv: 'media' },
  mkv: { '3gp': 'media', aac: 'media', ac3: 'media', aiff: 'media', au: 'media', avi: 'media', caf: 'media', eac3: 'media', flac: 'media', flv: 'media', gif: 'media', m4a: 'media', m4v: 'media', mka: 'media', mov: 'media', mp2: 'media', mp3: 'media', mp4: 'media', mpg: 'media', ogg: 'media', ogv: 'media', opus: 'media', spx: 'media', ts: 'media', tta: 'media', wav: 'media', webm: 'media', wma: 'media', wmv: 'media', wv: 'media' },
  mng: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  mobi: { azw3: 'ebook', docx: 'ebook', epub: 'ebook', fb2: 'ebook', htmlz: 'ebook', lit: 'ebook', lrf: 'ebook', pdb: 'ebook', pdf: 'ebook', pmlz: 'ebook', rb: 'ebook', rtf: 'ebook', tcr: 'ebook', txt: 'ebook', txtz: 'ebook' },
  mov: { '3gp': 'media', aac: 'media', ac3: 'media', aiff: 'media', au: 'media', avi: 'media', caf: 'media', eac3: 'media', flac: 'media', flv: 'media', gif: 'media', m4a: 'media', m4v: 'media', mka: 'media', mkv: 'media', mp2: 'media', mp3: 'media', mp4: 'media', mpg: 'media', ogg: 'media', ogv: 'media', opus: 'media', spx: 'media', ts: 'media', tta: 'media', wav: 'media', webm: 'media', wma: 'media', wmv: 'media', wv: 'media' },
  mp2: { aac: 'media', ac3: 'media', aiff: 'media', au: 'media', caf: 'media', eac3: 'media', flac: 'media', m4a: 'media', mka: 'media', mp3: 'media', ogg: 'media', opus: 'media', spx: 'media', tta: 'media', wav: 'media', wma: 'media', wv: 'media' },
  mp3: { aac: 'media', ac3: 'media', aiff: 'media', au: 'media', caf: 'media', eac3: 'media', flac: 'media', m4a: 'media', mka: 'media', mp2: 'media', ogg: 'media', opus: 'media', spx: 'media', tta: 'media', wav: 'media', wma: 'media', wv: 'media' },
  mp4: { '3gp': 'media', aac: 'media', ac3: 'media', aiff: 'media', au: 'media', avi: 'media', caf: 'media', eac3: 'media', flac: 'media', flv: 'media', gif: 'media', m4a: 'media', m4v: 'media', mka: 'media', mkv: 'media', mov: 'media', mp2: 'media', mp3: 'media', mpg: 'media', ogg: 'media', ogv: 'media', opus: 'media', spx: 'media', ts: 'media', tta: 'media', wav: 'media', webm: 'media', wma: 'media', wmv: 'media', wv: 'media' },
  mpeg: { '3gp': 'media', aac: 'media', ac3: 'media', aiff: 'media', au: 'media', avi: 'media', caf: 'media', eac3: 'media', flac: 'media', flv: 'media', gif: 'media', m4a: 'media', m4v: 'media', mka: 'media', mkv: 'media', mov: 'media', mp2: 'media', mp3: 'media', mp4: 'media', mpg: 'media', ogg: 'media', ogv: 'media', opus: 'media', spx: 'media', ts: 'media', tta: 'media', wav: 'media', webm: 'media', wma: 'media', wmv: 'media', wv: 'media' },
  mpg: { '3gp': 'media', aac: 'media', ac3: 'media', aiff: 'media', au: 'media', avi: 'media', caf: 'media', eac3: 'media', flac: 'media', flv: 'media', gif: 'media', m4a: 'media', m4v: 'media', mka: 'media', mkv: 'media', mov: 'media', mp2: 'media', mp3: 'media', mp4: 'media', ogg: 'media', ogv: 'media', opus: 'media', spx: 'media', ts: 'media', tta: 'media', wav: 'media', webm: 'media', wma: 'media', wmv: 'media', wv: 'media' },
  mts: { '3gp': 'media', aac: 'media', ac3: 'media', aiff: 'media', au: 'media', avi: 'media', caf: 'media', eac3: 'media', flac: 'media', flv: 'media', gif: 'media', m4a: 'media', m4v: 'media', mka: 'media', mkv: 'media', mov: 'media', mp2: 'media', mp3: 'media', mp4: 'media', mpg: 'media', ogg: 'media', ogv: 'media', opus: 'media', spx: 'media', ts: 'media', tta: 'media', wav: 'media', webm: 'media', wma: 'media', wmv: 'media', wv: 'media' },
  muse: { adoc: 'document', context: 'document', docbook: 'document', docx: 'document', dokuwiki: 'document', epub: 'document', fb2: 'document', gfm: 'document', html: 'document', icml: 'document', ipynb: 'document', jats: 'document', jira: 'document', json: 'document', man: 'document', markua: 'document', md: 'document', mediawiki: 'document', ms: 'document', odt: 'document', opml: 'document', org: 'document', rst: 'document', rtf: 'document', tei: 'document', tex: 'document', texi: 'document', textile: 'document', txt: 'document', typst: 'document', xwiki: 'document', zimwiki: 'document' },
  ndjson: { csv: 'data', json: 'data', tsv: 'data', yaml: 'data' },
  nut: { '3gp': 'media', aac: 'media', ac3: 'media', aiff: 'media', au: 'media', avi: 'media', caf: 'media', eac3: 'media', flac: 'media', flv: 'media', gif: 'media', m4a: 'media', m4v: 'media', mka: 'media', mkv: 'media', mov: 'media', mp2: 'media', mp3: 'media', mp4: 'media', mpg: 'media', ogg: 'media', ogv: 'media', opus: 'media', spx: 'media', ts: 'media', tta: 'media', wav: 'media', webm: 'media', wma: 'media', wmv: 'media', wv: 'media' },
  odp: { html: 'office', pdf: 'office', pptx: 'office' },
  ods: { csv: 'office', html: 'office', pdf: 'office', xlsx: 'office' },
  odt: { adoc: 'document', azw3: 'ebook', context: 'document', docbook: 'document', docx: 'office', dokuwiki: 'document', epub: 'document', fb2: 'document', gfm: 'document', html: 'document', htmlz: 'ebook', icml: 'document', ipynb: 'document', jats: 'document', jira: 'document', json: 'document', lit: 'ebook', lrf: 'ebook', man: 'document', markua: 'document', md: 'document', mediawiki: 'document', mobi: 'ebook', ms: 'document', muse: 'document', opml: 'document', org: 'document', pdb: 'ebook', pdf: 'office', pmlz: 'ebook', rb: 'ebook', rst: 'document', rtf: 'office', tcr: 'ebook', tei: 'document', tex: 'document', texi: 'document', textile: 'document', txt: 'document', txtz: 'ebook', typst: 'document', xwiki: 'document', zimwiki: 'document' },
  oga: { aac: 'media', ac3: 'media', aiff: 'media', au: 'media', caf: 'media', eac3: 'media', flac: 'media', m4a: 'media', mka: 'media', mp2: 'media', mp3: 'media', ogg: 'media', opus: 'media', spx: 'media', tta: 'media', wav: 'media', wma: 'media', wv: 'media' },
  ogg: { aac: 'media', ac3: 'media', aiff: 'media', au: 'media', caf: 'media', eac3: 'media', flac: 'media', m4a: 'media', mka: 'media', mp2: 'media', mp3: 'media', opus: 'media', spx: 'media', tta: 'media', wav: 'media', wma: 'media', wv: 'media' },
  ogv: { '3gp': 'media', aac: 'media', ac3: 'media', aiff: 'media', au: 'media', avi: 'media', caf: 'media', eac3: 'media', flac: 'media', flv: 'media', gif: 'media', m4a: 'media', m4v: 'media', mka: 'media', mkv: 'media', mov: 'media', mp2: 'media', mp3: 'media', mp4: 'media', mpg: 'media', ogg: 'media', opus: 'media', spx: 'media', ts: 'media', tta: 'media', wav: 'media', webm: 'media', wma: 'media', wmv: 'media', wv: 'media' },
  opml: { adoc: 'document', context: 'document', docbook: 'document', docx: 'document', dokuwiki: 'document', epub: 'document', fb2: 'document', gfm: 'document', html: 'document', icml: 'document', ipynb: 'document', jats: 'document', jira: 'document', json: 'document', man: 'document', md: 'document', mediawiki: 'document', ms: 'document', muse: 'document', odt: 'document', org: 'document', rst: 'document', rtf: 'document', tei: 'document', tex: 'document', texi: 'document', textile: 'document', txt: 'document', typst: 'document', zimwiki: 'document' },
  opus: { aac: 'media', ac3: 'media', aiff: 'media', au: 'media', caf: 'media', eac3: 'media', flac: 'media', m4a: 'media', mka: 'media', mp2: 'media', mp3: 'media', ogg: 'media', spx: 'media', tta: 'media', wav: 'media', wma: 'media', wv: 'media' },
  org: { adoc: 'document', context: 'document', docbook: 'document', docx: 'document', dokuwiki: 'document', epub: 'document', fb2: 'document', gfm: 'document', html: 'document', icml: 'document', ipynb: 'document', jats: 'document', jira: 'document', json: 'document', man: 'document', markua: 'document', md: 'document', mediawiki: 'document', ms: 'document', muse: 'document', odt: 'document', opml: 'document', rst: 'document', rtf: 'document', tei: 'document', tex: 'document', texi: 'document', textile: 'document', txt: 'document', typst: 'document', xwiki: 'document', zimwiki: 'document' },
  otb: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  otf: { ttx: 'font', woff: 'font', woff2: 'font' },
  palm: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  pbm: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  pcx: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  pdb: { azw3: 'ebook', docx: 'ebook', epub: 'ebook', fb2: 'ebook', htmlz: 'ebook', lit: 'ebook', lrf: 'ebook', mobi: 'ebook', pdf: 'ebook', pmlz: 'ebook', rb: 'ebook', rtf: 'ebook', tcr: 'ebook', txt: 'ebook', txtz: 'ebook' },
  pdf: { avif: 'image', azw3: 'ebook', bmp: 'image', dds: 'image', docx: 'ebook', eps: 'image', epub: 'ebook', fb2: 'ebook', gif: 'image', hdr: 'image', heic: 'image', htmlz: 'ebook', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', lit: 'ebook', lrf: 'ebook', miff: 'image', mobi: 'ebook', pbm: 'image', pcx: 'image', pdb: 'ebook', pgm: 'image', pmlz: 'ebook', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', rb: 'ebook', rtf: 'ebook', sgi: 'image', tcr: 'ebook', tga: 'image', tif: 'image', tiff: 'image', txt: 'ebook', txtz: 'ebook', wbmp: 'image', webp: 'image', xpm: 'image' },
  pgm: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  pict: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  pml: { azw3: 'ebook', docx: 'ebook', epub: 'ebook', fb2: 'ebook', htmlz: 'ebook', lit: 'ebook', lrf: 'ebook', mobi: 'ebook', pdb: 'ebook', pdf: 'ebook', pmlz: 'ebook', rb: 'ebook', rtf: 'ebook', tcr: 'ebook', txt: 'ebook', txtz: 'ebook' },
  pmlz: { azw3: 'ebook', docx: 'ebook', epub: 'ebook', fb2: 'ebook', htmlz: 'ebook', lit: 'ebook', lrf: 'ebook', mobi: 'ebook', pdb: 'ebook', pdf: 'ebook', rb: 'ebook', rtf: 'ebook', tcr: 'ebook', txt: 'ebook', txtz: 'ebook' },
  png: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  pnm: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  ppm: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  ppt: { html: 'office', odp: 'office', pdf: 'office', pptx: 'office' },
  pptx: { html: 'office', odp: 'office', pdf: 'office' },
  prc: { azw3: 'ebook', docx: 'ebook', epub: 'ebook', fb2: 'ebook', htmlz: 'ebook', lit: 'ebook', lrf: 'ebook', mobi: 'ebook', pdb: 'ebook', pdf: 'ebook', pmlz: 'ebook', rb: 'ebook', rtf: 'ebook', tcr: 'ebook', txt: 'ebook', txtz: 'ebook' },
  psd: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  ras: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  rb: { azw3: 'ebook', docx: 'ebook', epub: 'ebook', fb2: 'ebook', htmlz: 'ebook', lit: 'ebook', lrf: 'ebook', mobi: 'ebook', pdb: 'ebook', pdf: 'ebook', pmlz: 'ebook', rtf: 'ebook', tcr: 'ebook', txt: 'ebook', txtz: 'ebook' },
  ris: { biblatex: 'bibliography', bibtex: 'bibliography', csljson: 'bibliography' },
  rm: { '3gp': 'media', aac: 'media', ac3: 'media', aiff: 'media', au: 'media', avi: 'media', caf: 'media', eac3: 'media', flac: 'media', flv: 'media', gif: 'media', m4a: 'media', m4v: 'media', mka: 'media', mkv: 'media', mov: 'media', mp2: 'media', mp3: 'media', mp4: 'media', mpg: 'media', ogg: 'media', ogv: 'media', opus: 'media', spx: 'media', ts: 'media', tta: 'media', wav: 'media', webm: 'media', wma: 'media', wmv: 'media', wv: 'media' },
  rst: { adoc: 'document', context: 'document', docbook: 'document', docx: 'document', dokuwiki: 'document', epub: 'document', fb2: 'document', gfm: 'document', html: 'document', icml: 'document', ipynb: 'document', jats: 'document', jira: 'document', json: 'document', man: 'document', markua: 'document', md: 'document', mediawiki: 'document', ms: 'document', muse: 'document', odt: 'document', opml: 'document', org: 'document', rtf: 'document', tei: 'document', tex: 'document', texi: 'document', textile: 'document', txt: 'document', typst: 'document', xwiki: 'document', zimwiki: 'document' },
  rtf: { adoc: 'document', azw3: 'ebook', context: 'document', docbook: 'document', docx: 'office', dokuwiki: 'document', epub: 'document', fb2: 'document', gfm: 'document', html: 'document', htmlz: 'ebook', icml: 'document', ipynb: 'document', jats: 'document', jira: 'document', json: 'document', lit: 'ebook', lrf: 'ebook', man: 'document', md: 'document', mediawiki: 'document', mobi: 'ebook', ms: 'document', muse: 'document', odt: 'office', opml: 'document', org: 'document', pdb: 'ebook', pdf: 'office', pmlz: 'ebook', rb: 'ebook', rst: 'document', tcr: 'ebook', tei: 'document', tex: 'document', texi: 'document', textile: 'document', txt: 'document', txtz: 'ebook', typst: 'document', zimwiki: 'document' },
  sgi: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  spx: { ac3: 'media', aiff: 'media', au: 'media', caf: 'media', eac3: 'media', flac: 'media', mka: 'media', mp2: 'media', mp3: 'media', ogg: 'media', opus: 'media', tta: 'media', wav: 'media', wma: 'media', wv: 'media' },
  srt: { ass: 'subtitle', lrc: 'subtitle', ssa: 'subtitle', ttml: 'subtitle', vtt: 'subtitle' },
  ssa: { ass: 'subtitle', lrc: 'subtitle', srt: 'subtitle', ttml: 'subtitle', vtt: 'subtitle' },
  svg: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  swf: { '3gp': 'media', avi: 'media', flv: 'media', gif: 'media', m4v: 'media', mkv: 'media', mov: 'media', mp4: 'media', mpg: 'media', ogv: 'media', ts: 'media', webm: 'media', wmv: 'media' },
  t2t: { context: 'document', docbook: 'document', docx: 'document', dokuwiki: 'document', epub: 'document', fb2: 'document', gfm: 'document', html: 'document', icml: 'document', ipynb: 'document', jats: 'document', jira: 'document', json: 'document', man: 'document', md: 'document', mediawiki: 'document', ms: 'document', muse: 'document', odt: 'document', org: 'document', rst: 'document', rtf: 'document', tei: 'document', tex: 'document', texi: 'document', textile: 'document', txt: 'document', typst: 'document', zimwiki: 'document' },
  tar: { '7z': 'archive', tbz2: 'archive', tgz: 'archive', txz: 'archive', zip: 'archive' },
  tbz2: { '7z': 'archive', tar: 'archive', tgz: 'archive', txz: 'archive', zip: 'archive' },
  tcr: { azw3: 'ebook', docx: 'ebook', epub: 'ebook', fb2: 'ebook', htmlz: 'ebook', lit: 'ebook', lrf: 'ebook', mobi: 'ebook', pdb: 'ebook', pdf: 'ebook', pmlz: 'ebook', rb: 'ebook', rtf: 'ebook', txt: 'ebook', txtz: 'ebook' },
  tex: { adoc: 'document', context: 'document', docbook: 'document', docx: 'document', dokuwiki: 'document', epub: 'document', fb2: 'document', gfm: 'document', html: 'document', icml: 'document', ipynb: 'document', jats: 'document', jira: 'document', json: 'document', man: 'document', markua: 'document', md: 'document', mediawiki: 'document', ms: 'document', muse: 'document', odt: 'document', opml: 'document', org: 'document', rst: 'document', rtf: 'document', tei: 'document', texi: 'document', textile: 'document', txt: 'document', typst: 'document', xwiki: 'document', zimwiki: 'document' },
  textile: { adoc: 'document', context: 'document', docbook: 'document', docx: 'document', dokuwiki: 'document', epub: 'document', fb2: 'document', gfm: 'document', html: 'document', icml: 'document', ipynb: 'document', jats: 'document', jira: 'document', json: 'document', man: 'document', markua: 'document', md: 'document', mediawiki: 'document', ms: 'document', muse: 'document', odt: 'document', opml: 'document', org: 'document', rst: 'document', rtf: 'document', tei: 'document', tex: 'document', texi: 'document', txt: 'document', typst: 'document', xwiki: 'document', zimwiki: 'document' },
  tga: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  tgz: { '7z': 'archive', tar: 'archive', tbz2: 'archive', txz: 'archive', zip: 'archive' },
  tif: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  tiff: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  toml: { json: 'data', yaml: 'data' },
  ts: { '3gp': 'media', aac: 'media', ac3: 'media', aiff: 'media', au: 'media', avi: 'media', caf: 'media', eac3: 'media', flac: 'media', flv: 'media', gif: 'media', m4a: 'media', m4v: 'media', mka: 'media', mkv: 'media', mov: 'media', mp2: 'media', mp3: 'media', mp4: 'media', mpg: 'media', ogg: 'media', ogv: 'media', opus: 'media', spx: 'media', tta: 'media', wav: 'media', webm: 'media', wma: 'media', wmv: 'media', wv: 'media' },
  tsv: { context: 'document', csv: 'data', docbook: 'document', docx: 'document', dokuwiki: 'document', epub: 'document', gfm: 'document', html: 'document', icml: 'document', ipynb: 'document', jats: 'document', jira: 'document', json: 'data', man: 'document', md: 'document', mediawiki: 'document', ms: 'document', muse: 'document', ndjson: 'data', odt: 'document', org: 'document', rst: 'document', rtf: 'document', tei: 'document', tex: 'document', texi: 'document', textile: 'document', txt: 'document', typst: 'document', yaml: 'data', zimwiki: 'document' },
  tta: { ac3: 'media', aiff: 'media', au: 'media', caf: 'media', eac3: 'media', flac: 'media', mka: 'media', mp3: 'media', ogg: 'media', opus: 'media', spx: 'media', wav: 'media', wma: 'media', wv: 'media' },
  ttc: { ttf: 'font', ttx: 'font', woff: 'font', woff2: 'font' },
  ttf: { ttx: 'font', woff: 'font', woff2: 'font' },
  twiki: { adoc: 'document', context: 'document', docbook: 'document', docx: 'document', dokuwiki: 'document', epub: 'document', fb2: 'document', gfm: 'document', html: 'document', icml: 'document', ipynb: 'document', jats: 'document', jira: 'document', json: 'document', man: 'document', markua: 'document', md: 'document', mediawiki: 'document', ms: 'document', muse: 'document', odt: 'document', opml: 'document', org: 'document', rst: 'document', rtf: 'document', tei: 'document', tex: 'document', texi: 'document', textile: 'document', txt: 'document', typst: 'document', xwiki: 'document', zimwiki: 'document' },
  txt: { azw3: 'ebook', context: 'document', docbook: 'document', docx: 'document', dokuwiki: 'document', epub: 'document', fb2: 'document', gfm: 'document', html: 'document', htmlz: 'ebook', icml: 'document', ipynb: 'document', jats: 'document', jira: 'document', json: 'document', lit: 'ebook', lrf: 'ebook', man: 'document', md: 'document', mediawiki: 'document', mobi: 'ebook', ms: 'document', muse: 'document', odt: 'document', org: 'document', pdb: 'ebook', pdf: 'ebook', pmlz: 'ebook', rb: 'ebook', rst: 'document', rtf: 'document', tcr: 'ebook', tei: 'document', tex: 'document', texi: 'document', textile: 'document', txtz: 'ebook', typst: 'document', zimwiki: 'document' },
  txtz: { azw3: 'ebook', docx: 'ebook', epub: 'ebook', fb2: 'ebook', htmlz: 'ebook', lit: 'ebook', lrf: 'ebook', mobi: 'ebook', pdb: 'ebook', pdf: 'ebook', pmlz: 'ebook', rb: 'ebook', rtf: 'ebook', tcr: 'ebook', txt: 'ebook' },
  txz: { '7z': 'archive', tar: 'archive', tbz2: 'archive', tgz: 'archive', zip: 'archive' },
  typst: { adoc: 'document', context: 'document', docbook: 'document', docx: 'document', dokuwiki: 'document', epub: 'document', fb2: 'document', gfm: 'document', html: 'document', icml: 'document', ipynb: 'document', jats: 'document', jira: 'document', json: 'document', man: 'document', markua: 'document', md: 'document', mediawiki: 'document', ms: 'document', muse: 'document', odt: 'document', opml: 'document', org: 'document', rst: 'document', rtf: 'document', tei: 'document', tex: 'document', texi: 'document', textile: 'document', txt: 'document', xwiki: 'document', zimwiki: 'document' },
  vimwiki: { adoc: 'document', context: 'document', docbook: 'document', docx: 'document', dokuwiki: 'document', epub: 'document', fb2: 'document', gfm: 'document', html: 'document', icml: 'document', ipynb: 'document', jats: 'document', jira: 'document', json: 'document', man: 'document', markua: 'document', md: 'document', mediawiki: 'document', ms: 'document', muse: 'document', odt: 'document', opml: 'document', org: 'document', rst: 'document', rtf: 'document', tei: 'document', tex: 'document', texi: 'document', textile: 'document', txt: 'document', typst: 'document', xwiki: 'document', zimwiki: 'document' },
  vob: { '3gp': 'media', aac: 'media', ac3: 'media', aiff: 'media', au: 'media', avi: 'media', caf: 'media', eac3: 'media', flac: 'media', flv: 'media', gif: 'media', m4a: 'media', m4v: 'media', mka: 'media', mkv: 'media', mov: 'media', mp2: 'media', mp3: 'media', mp4: 'media', mpg: 'media', ogg: 'media', ogv: 'media', opus: 'media', spx: 'media', ts: 'media', tta: 'media', wav: 'media', webm: 'media', wma: 'media', wmv: 'media', wv: 'media' },
  voc: { aac: 'media', ac3: 'media', aiff: 'media', au: 'media', caf: 'media', eac3: 'media', flac: 'media', m4a: 'media', mka: 'media', mp2: 'media', mp3: 'media', ogg: 'media', opus: 'media', spx: 'media', tta: 'media', wav: 'media', wma: 'media', wv: 'media' },
  vtt: { ass: 'subtitle', lrc: 'subtitle', srt: 'subtitle', ssa: 'subtitle', ttml: 'subtitle' },
  w64: { aac: 'media', ac3: 'media', aiff: 'media', au: 'media', caf: 'media', eac3: 'media', flac: 'media', m4a: 'media', mka: 'media', mp2: 'media', mp3: 'media', ogg: 'media', opus: 'media', spx: 'media', tta: 'media', wav: 'media', wma: 'media', wv: 'media' },
  wav: { aac: 'media', ac3: 'media', aiff: 'media', au: 'media', caf: 'media', eac3: 'media', flac: 'media', m4a: 'media', mka: 'media', mp2: 'media', mp3: 'media', ogg: 'media', opus: 'media', spx: 'media', tta: 'media', wma: 'media', wv: 'media' },
  wbmp: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', webp: 'image', xpm: 'image' },
  webm: { '3gp': 'media', aac: 'media', ac3: 'media', aiff: 'media', au: 'media', avi: 'media', caf: 'media', eac3: 'media', flac: 'media', flv: 'media', gif: 'media', m4a: 'media', m4v: 'media', mka: 'media', mkv: 'media', mov: 'media', mp2: 'media', mp3: 'media', mp4: 'media', mpg: 'media', ogg: 'media', ogv: 'media', opus: 'media', spx: 'media', ts: 'media', tta: 'media', wav: 'media', wma: 'media', wmv: 'media', wv: 'media' },
  webp: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', xpm: 'image' },
  wma: { aac: 'media', ac3: 'media', aiff: 'media', au: 'media', caf: 'media', eac3: 'media', flac: 'media', m4a: 'media', mka: 'media', mp2: 'media', mp3: 'media', ogg: 'media', opus: 'media', spx: 'media', tta: 'media', wav: 'media', wv: 'media' },
  wmv: { '3gp': 'media', aac: 'media', ac3: 'media', aiff: 'media', au: 'media', avi: 'media', caf: 'media', eac3: 'media', flac: 'media', flv: 'media', gif: 'media', m4a: 'media', m4v: 'media', mka: 'media', mkv: 'media', mov: 'media', mp2: 'media', mp3: 'media', mp4: 'media', mpg: 'media', ogg: 'media', ogv: 'media', opus: 'media', spx: 'media', ts: 'media', tta: 'media', wav: 'media', webm: 'media', wma: 'media', wv: 'media' },
  woff: { otf: 'font', ttf: 'font', ttx: 'font', woff2: 'font' },
  woff2: { otf: 'font', ttf: 'font', ttx: 'font', woff: 'font' },
  wv: { aac: 'media', ac3: 'media', aiff: 'media', au: 'media', caf: 'media', eac3: 'media', flac: 'media', m4a: 'media', mka: 'media', mp2: 'media', mp3: 'media', ogg: 'media', opus: 'media', spx: 'media', tta: 'media', wav: 'media', wma: 'media' },
  xbm: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image', xpm: 'image' },
  xhtml: { adoc: 'document', context: 'document', docbook: 'document', docx: 'document', dokuwiki: 'document', epub: 'document', fb2: 'document', gfm: 'document', html: 'document', icml: 'document', ipynb: 'document', jats: 'document', jira: 'document', json: 'document', man: 'document', markua: 'document', md: 'document', mediawiki: 'document', ms: 'document', muse: 'document', odt: 'document', opml: 'document', org: 'document', rst: 'document', rtf: 'document', tei: 'document', tex: 'document', texi: 'document', textile: 'document', txt: 'document', typst: 'document', xwiki: 'document', zimwiki: 'document' },
  xls: { csv: 'office', html: 'office', ods: 'office', pdf: 'office', xlsx: 'office' },
  xlsx: { csv: 'office', html: 'office', ods: 'office', pdf: 'office' },
  xpm: { avif: 'image', bmp: 'image', dds: 'image', eps: 'image', gif: 'image', hdr: 'image', heic: 'image', ico: 'image', jng: 'image', jp2: 'image', jpeg: 'image', jpg: 'image', miff: 'image', pbm: 'image', pcx: 'image', pdf: 'image', pgm: 'image', png: 'image', pnm: 'image', ppm: 'image', ps: 'image', psd: 'image', ras: 'image', sgi: 'image', tga: 'image', tif: 'image', tiff: 'image', wbmp: 'image', webp: 'image' },
  y4m: { '3gp': 'media', avi: 'media', flv: 'media', gif: 'media', m4v: 'media', mkv: 'media', mov: 'media', mp4: 'media', mpg: 'media', ogv: 'media', ts: 'media', webm: 'media', wmv: 'media' },
  yaml: { csv: 'data', json: 'data', ndjson: 'data', toml: 'data', tsv: 'data' },
  zip: { '7z': 'archive', tar: 'archive', tbz2: 'archive', tgz: 'archive', txz: 'archive' },
};

/** Nombre de paires servies et des extensions sources.
 *
 * Calcules, jamais recopies : ces deux chiffres ont figure en dur
 * dans cinq fichiers, dont le texte publie des pages, et y ont
 * vieilli sans que rien ne le signale. */
export const NOMBRE_DE_PAIRES = 3649;
export const NOMBRE_DE_SOURCES = 162;

/** Cibles facturees a la minute de source, et elles seules. */
export const CIBLES_A_LA_MINUTE = new Set(['3gp', 'avi', 'flv', 'gif', 'm4v', 'mkv', 'mov', 'mp4', 'mpg', 'ogv', 'ts', 'webm', 'wmv']);

// Exportee, parce qu'elle a ete RECOPIEE A LA MAIN quatre fois : dans le
// test du README du serveur MCP (trois copies) et dans son test des
// routes. Chacune est restee en arriere d'une famille au moins une fois,
// et un test qui ne voit pas une route ne la garde pas.
export const ROUTES = {
  image: '/api/convert-image',
  ebook: '/api/convert-ebook',
  document: '/api/convert-document',
  // Toute la famille passe par convert-office, PDF compris : une paire,
  // une route. /api/convert-to-pdf existe toujours et reste appelee par
  // la page « Office to PDF », mais elle n'est plus une destination de la
  // table, sans quoi deux routes serviraient les memes onze paires et
  // deriveraient l'une de l'autre.
  office: '/api/convert-office',
  font: '/api/convert-font',
  archive: '/api/convert-archive',
  data: '/api/convert-data',
  subtitle: '/api/convert-subtitle',
  bibliography: '/api/convert-bibliography',
  media: '/api/convert-media',
};

const normaliser = (e) => String(e || '').toLowerCase().replace(/^\./, '');

/** Cibles prouvees pour cette extension, triees. [] si on ne sait pas la lire. */
export function ciblesPour(extension) {
  const t = PAIRES[normaliser(extension)];
  return t ? Object.keys(t).sort() : [];
}

/** Route qui sert cette paire, ou null si elle n'est pas prouvee. */
export function routePour(extension, cible) {
  const t = PAIRES[normaliser(extension)];
  const famille = t && t[normaliser(cible)];
  return famille ? ROUTES[famille] : null;
}

/** Toutes les extensions acceptees, triees. */
export function sourcesConnues() {
  return Object.keys(PAIRES).sort();
}

/** Vrai quand cette paire est facturee a la minute et non a l'appel. */
export function estALaMinute(extension, cible) {
  return routePour(extension, cible) === '/api/convert-media'
    && CIBLES_A_LA_MINUTE.has(normaliser(cible));
}

export default PAIRES;
